package studio.rrprojects.runnerbuddy.gui.popups;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import org.json.JSONObject;
import studio.rrprojects.runnerbuddy.containers.character.CharacterContainer;
import studio.rrprojects.runnerbuddy.containers.gear.GearContainer;
import studio.rrprojects.runnerbuddy.gui.cards.GearCard;
import studio.rrprojects.runnerbuddy.utils.TextUtils;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Map;
import java.util.Objects;

public class EditGearPopup {
    private GearCard gearCard;
    private CharacterContainer character;
    private GearContainer gear;
    private JTextPane textDescription;
    private JButton buttonCancel;
    private JButton buttonSubmit;
    private JPanel panelMain;
    private JLabel textRating;
    private JComboBox<Serializable> boxRating;
    private ArrayList<String> descriptionArray;

    public EditGearPopup(GearContainer baseGear, CharacterContainer character, GearCard gearCard) {
        gear = baseGear;
        this.character = character;
        this.gearCard = gearCard;

        PopulateDescription();

        CheckVariableRating();

        JFrame frame = new JFrame();
        frame.setContentPane(panelMain);
        frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        frame.setVisible(true);
        frame.pack();
        buttonSubmit.addActionListener(e -> Submit(frame, gear));
    }

    private void Submit(JFrame frame, GearContainer gear) {
        gear.setItemRating(Objects.requireNonNull(boxRating.getSelectedItem()).toString());
        character.getGearController().AddNewGear(gear);
        gearCard.UpdateAll();
        frame.dispose();
    }

    private void CheckVariableRating() {
        boolean b = gear.getJsonObject().getBoolean("variable_rating");
        textRating.setEnabled(b);
        boxRating.setEnabled(b);

        CheckRatingOverride();
    }

    private void CheckRatingOverride() {
        ArrayList<String> exceptionList = new ArrayList<>();
        exceptionList.add("Standard Bow");

        if (exceptionList.contains(gear.getItemName())) {
            DefaultComboBoxModel<Serializable> box = new DefaultComboBoxModel<>();
            for (int i = 1; i < 21; i++) {
                box.addElement(i);
            }
            boxRating.setModel(box);
        }
    }

    private void PopulateDescription() {
        StringBuilder descriptionBody = new StringBuilder();
        descriptionArray = new ArrayList<>();

        JSONObject object = gear.getJsonObject();
        Map<String, Object> map = object.toMap();

        map.forEach((key, value) -> descriptionArray.add(TextUtils.PrettyKey(key) + ": " + value));

        Collections.sort(descriptionArray);

        descriptionBody.append("Name: ").append(gear.getItemName()).append("\n\n");

        for (String line : descriptionArray) {
            descriptionBody.append(line).append("\n\n");
        }

        textDescription.setText(String.valueOf(descriptionBody));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelMain = new JPanel();
        panelMain.setLayout(new GridLayoutManager(3, 5, new Insets(0, 0, 0, 0), -1, -1));
        panelMain.setBackground(new Color(-14079180));
        panelMain.setPreferredSize(new Dimension(400, 600));
        buttonSubmit = new JButton();
        buttonSubmit.setBackground(new Color(-14079180));
        buttonSubmit.setForeground(new Color(-11805347));
        buttonSubmit.setText("Submit");
        panelMain.add(buttonSubmit, new GridConstraints(2, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonCancel = new JButton();
        buttonCancel.setBackground(new Color(-14079180));
        buttonCancel.setForeground(new Color(-11805347));
        buttonCancel.setText("Cancel");
        panelMain.add(buttonCancel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panelMain.add(spacer1, new GridConstraints(2, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        textDescription = new JTextPane();
        textDescription.setBackground(new Color(-14079180));
        textDescription.setForeground(new Color(-11805347));
        panelMain.add(textDescription, new GridConstraints(0, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        textRating = new JLabel();
        textRating.setBackground(new Color(-14079180));
        textRating.setForeground(new Color(-11805347));
        textRating.setText("Rating:");
        panelMain.add(textRating, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        boxRating = new JComboBox();
        boxRating.setBackground(new Color(-14079180));
        boxRating.setForeground(new Color(-11805347));
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("1");
        defaultComboBoxModel1.addElement("2");
        defaultComboBoxModel1.addElement("3");
        defaultComboBoxModel1.addElement("4");
        defaultComboBoxModel1.addElement("5");
        defaultComboBoxModel1.addElement("6");
        boxRating.setModel(defaultComboBoxModel1);
        panelMain.add(boxRating, new GridConstraints(1, 4, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelMain;
    }

}
