package studio.rrprojects.runnerbuddy.gui.popups;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import studio.rrprojects.runnerbuddy.containers.character.CharacterContainer;
import studio.rrprojects.runnerbuddy.controllers.PriorityController;
import studio.rrprojects.runnerbuddy.gui.popups.components.PriorityModule;
import studio.rrprojects.runnerbuddy.misc.PriorityOptions;

import javax.swing.*;
import java.awt.*;
import java.util.LinkedHashMap;
import java.util.Map;

public class NewCharacterPriorityPopup extends JFrame {
    private JPanel panelMain;
    private JLabel labelHeader;
    private JButton buttonCancel;
    private JButton buttonSubmit;
    private JPanel panelPrimary;
    private CharacterContainer characterContainer;
    private LinkedHashMap<String, PriorityModule> priorityModuleMasterList;
    private PriorityOptions priorityOptions;

    public NewCharacterPriorityPopup(String title, CharacterContainer characterContainer) {
        super(title);
        this.characterContainer = characterContainer;

        setContentPane(panelMain);
        setDefaultCloseOperation(EXIT_ON_CLOSE);


        Initialize();

        pack();
        setSize(900, 400);
        setVisible(true);
    }

    private void Initialize() {
        PriorityController priorityController = characterContainer.getPriorityController();
        String[] priorityLevelList = {"a", "b", "c", "d", "e"};
        priorityModuleMasterList = new LinkedHashMap<>();

        for (String priorityLevel : priorityLevelList) {
            priorityOptions = priorityController.getOptionsByLevel(priorityLevel);
            priorityModuleMasterList.put(priorityLevel, new PriorityModule(priorityLevel, priorityOptions));
        }

        panelPrimary.setLayout(new GridLayout(0, 1, 0, 10));

        for (Map.Entry<String, PriorityModule> entry : priorityModuleMasterList.entrySet()) {
            AddNewComponent(entry.getValue());
        }
    }

    private void AddNewComponent(PriorityModule priorityModule) {
        panelPrimary.add(priorityModule);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelMain = new JPanel();
        panelMain.setLayout(new GridLayoutManager(3, 2, new Insets(10, 10, 10, 10), -1, -1));
        panelMain.setMinimumSize(new Dimension(-1, -1));
        panelMain.setPreferredSize(new Dimension(-1, -1));
        labelHeader = new JLabel();
        labelHeader.setText("Shadowrun 3e Character Creation: Priority");
        panelMain.add(labelHeader, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonCancel = new JButton();
        buttonCancel.setText("Cancel");
        panelMain.add(buttonCancel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonSubmit = new JButton();
        buttonSubmit.setText("Submit");
        panelMain.add(buttonSubmit, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panelPrimary = new JPanel();
        panelPrimary.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelMain.add(panelPrimary, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelMain;
    }

}
