package studio.rrprojects.runnerbuddy.gui.popups.components;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import org.json.JSONObject;
import studio.rrprojects.runnerbuddy.containers.character.CharacterContainer;
import studio.rrprojects.runnerbuddy.controllers.PriorityController;
import studio.rrprojects.runnerbuddy.misc.PriorityOption;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.HashMap;

public class PriorityModule extends JPanel {
    private JComboBox boxPriorityOption;
    private JComboBox boxSubOption;
    private JLabel labelPriority;
    private JPanel panelMain;
    private CharacterContainer characterContainer;
    private ArrayList<PriorityOption> listOptions;
    private String priorityKey;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelMain = new JPanel();
        panelMain.setLayout(new GridLayoutManager(1, 5, new Insets(0, 0, 0, 0), -1, -1));
        labelPriority = new JLabel();
        labelPriority.setText("Priority");
        panelMain.add(labelPriority, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panelMain.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        boxPriorityOption = new JComboBox();
        panelMain.add(boxPriorityOption, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panelMain.add(spacer2, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        boxSubOption = new JComboBox();
        panelMain.add(boxSubOption, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelMain;
    }

    public void initialize(String priorityKey, PriorityController priorityController) {
        String name = "Priority " + priorityKey.toUpperCase() + ":";
    }

    public void initialize(JSONObject priorityKey) {
        for (String key : priorityKey.keySet()) {
            System.out.println("Key: " + key + ", Value: " + priorityKey.get(key).toString());
        }
    }

    public void SetPriority(CharacterContainer characterContainer, String priorityKey) {
        this.characterContainer = characterContainer;
        this.priorityKey = priorityKey;
        listOptions = characterContainer.getPriorityController().getOptionsByLevel(priorityKey);

        Format();
    }

    private void Format() {
        //TODO FINISH THIS
        labelPriority.setText("Priority " + priorityKey);
        boxSubOption.setEnabled(false);

        DefaultListCellRenderer listRenderer = new DefaultListCellRenderer();
        listRenderer.setHorizontalAlignment(DefaultListCellRenderer.CENTER); // center-aligned items
        boxPriorityOption.setRenderer(listRenderer);

        boxPriorityOption.setModel(GenerateModel());
        repaint();
    }

    private ComboBoxModel GenerateModel() {
        DefaultComboBoxModel tmp = new DefaultComboBoxModel();
        tmp.addElement("== Select An Option ==");
        //TODO BREAKING HERE !
        for (PriorityOption priorityOption : listOptions) {
            tmp.addElement(priorityOption.getPriorityCategory() + ": " + priorityOption.getDisplayString());
        }
        return tmp;
    }
}
