package studio.rrprojects.runnerbuddy.gui.cards.components;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class SmallProgressBar extends JComponent {
    private final TitledBorder titledBorder;
    private JLabel labelTitle;
    private JProgressBar progressBar;
    private JLabel labelValue;
    private JPanel panelMain;
    private JLabel labelWarning;
    private int valueMin = 0;
    private int valueMax = 1;
    private int value = 0;

    public SmallProgressBar() {
        titledBorder = BorderFactory.createTitledBorder("Title");
        panelMain.setBorder(titledBorder);
    }

    public void setTitle(String s) {
        titledBorder.setTitle(s);
    }

    public void setMin(int i) {
        valueMin = i;
        progressBar.setMinimum(i);
    }

    public void setMax(int i) {
        valueMax = i;
        progressBar.setMaximum(i);
    }

    public void setValue(int i) {
        value = i;

        UpdateBar();
        UpdateValueString();
    }

    private void UpdateBar() {
        progressBar.setValue(value);
    }

    public void UpdateValueString() {
        String stringValue = value + "/" + valueMax;
        labelValue.setText(stringValue);

        labelWarning.setVisible(false);
        if (value < valueMax) {
            progressBar.setForeground(Color.BLUE);
        } else if (value == valueMax) {
            progressBar.setForeground(Color.GREEN);
        } else {
            labelWarning.setVisible(true);
            progressBar.setForeground(Color.RED);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelMain = new JPanel();
        panelMain.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        progressBar = new JProgressBar();
        panelMain.add(progressBar, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelValue = new JLabel();
        labelValue.setText("Label");
        panelMain.add(labelValue, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelWarning = new JLabel();
        labelWarning.setText("WARNING: INVALID CHARACTER");
        panelMain.add(labelWarning, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelMain;
    }

    public int getValue() {
        return value;
    }

    public int getValueMax() {
        return valueMax;
    }
}
