package studio.rrprojects.runnerbuddy.gui.cards.magic;

import studio.rrprojects.runnerbuddy.gui.CardManager;
import studio.rrprojects.runnerbuddy.gui.cards.Card;

import javax.swing.*;
import java.awt.*;


public class MagicCard extends Card {
    private final JButton jButton;
    private JPanel panelMain;

    public MagicCard(String title) {
        super(title);
        setPanel(panelMain);
        jButton = new JButton(title);
    }

    @Override
    public void Initialize() {
        super.Initialize();

        CheckMagical();

        CardManager cardManager = new CardManager(panelMain);

        cardManager.setCharacterContainer(getCharacterContainer());

        cardManager.addCard(new MagicalInfoCard("Magic Info"));
        cardManager.addCard(new SpellsCard("Spells"));

    }

    private void CheckMagical() {
        jButton.setVisible(getCharacterContainer().getMagicController().isMagical());
    }

    @Override
    public void Update() {
        super.Update();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelMain = new JPanel();
        panelMain.setLayout(new CardLayout(0, 0));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelMain;
    }

    @Override
    public JButton getButton() {
        return jButton;
    }
}
